import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowUpRight, CheckCircle2, CircleAlert, Clock3, Loader2, Music2, PackageSearch, Plus, ShieldCheck, UsersRound, WalletCards, Zap } from "lucide-react";
import { FormEvent, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

function money(value: unknown, currency = "EUR") {
  return new Intl.NumberFormat("es-ES", { style: "currency", currency }).format(Number(value ?? 0));
}

function Empty({ label }: { label: string }) {
  return <div className="rounded-2xl border border-dashed border-border bg-muted/30 p-8 text-center text-sm text-muted-foreground">{label}</div>;
}

function Header({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) {
  return <div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 text-[10px] font-extrabold tracking-[0.2em] text-primary uppercase">{eyebrow}</p><h1 className="display-face text-4xl font-semibold tracking-tight md:text-5xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{copy}</p></div>{action}</div>;
}

function CreateClient() {
  const utils = trpc.useUtils();
  const create = trpc.studio.crm.createClient.useMutation({ onSuccess: () => { utils.studio.crm.listClients.invalidate(); toast.success("Cliente añadido al CRM."); } });
  const [open, setOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ name: String(data.get("name")), email: String(data.get("email")), artistName: String(data.get("artistName") || "") || undefined, tags: String(data.get("tags") || "").split(",").map(x => x.trim()).filter(Boolean), notes: String(data.get("notes") || "") || undefined }); event.currentTarget.reset(); setOpen(false); };
  return <div>{open ? <Card className="mb-5"><CardContent className="pt-6"><form className="grid gap-3 md:grid-cols-2" onSubmit={submit}><Input name="name" placeholder="Nombre o empresa" required /><Input name="email" type="email" placeholder="Email" required /><Input name="artistName" placeholder="Nombre artístico (opcional)" /><Input name="tags" placeholder="Etiquetas separadas por coma" /><Textarea className="md:col-span-2" name="notes" placeholder="Notas internas" /><div className="md:col-span-2 flex gap-2"><Button type="submit" disabled={create.isPending}>{create.isPending ? "Guardando…" : "Guardar cliente"}</Button><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancelar</Button></div></form></CardContent></Card> : <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Nuevo cliente</Button>}</div>;
}

function CrmView() {
  const { data, isLoading } = trpc.studio.crm.listClients.useQuery();
  return <><Header eyebrow="Relación" title="CRM de Duck" copy="Clientes, artistas y contactos concentrados en un único sistema. No se importa ni mezcla información de otras identidades." action={<CreateClient />} />{isLoading ? <Loader2 className="animate-spin" /> : !data?.length ? <Empty label="Aún no hay clientes. Crea el primer contacto real desde el botón superior." /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.map(client => <Card key={client.id} className="overflow-hidden"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="font-bold">{client.name}</p><p className="mt-1 text-sm text-muted-foreground">{client.artistName || client.email}</p></div><Badge variant="secondary">CRM</Badge></div><div className="mt-5 flex flex-wrap gap-1">{(client.tags || []).map(tag => <Badge key={tag} variant="outline">{tag}</Badge>)}</div></CardContent></Card>)}</div>}</>;
}

function CreateProject() {
  const utils = trpc.useUtils();
  const clients = trpc.studio.crm.listClients.useQuery();
  const create = trpc.studio.operations.createProject.useMutation({ onSuccess: () => { utils.studio.operations.listProjects.invalidate(); toast.success("Proyecto creado."); } });
  const [open, setOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ clientId: Number(data.get("clientId")), name: String(data.get("name")), service: String(data.get("service")), price: String(data.get("price") || "0"), currency: "EUR", description: String(data.get("description") || "") || undefined }); event.currentTarget.reset(); setOpen(false); };
  return <div>{open ? <Card className="mb-5"><CardContent className="pt-6"><form className="grid gap-3 md:grid-cols-2" onSubmit={submit}><select className="h-10 rounded-md border bg-background px-3 text-sm" name="clientId" required defaultValue=""><option disabled value="">Selecciona cliente</option>{clients.data?.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select><Input name="name" placeholder="Nombre del proyecto" required /><Input name="service" defaultValue="Producción musical" required /><Input name="price" type="number" min="0" step="0.01" placeholder="Importe" /><Textarea className="md:col-span-2" name="description" placeholder="Objetivo, alcance y referencias" /><div className="md:col-span-2 flex gap-2"><Button type="submit" disabled={create.isPending || !clients.data?.length}>Crear proyecto</Button><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancelar</Button></div></form></CardContent></Card> : <Button onClick={() => setOpen(true)} disabled={!clients.data?.length}><Plus className="mr-2 h-4 w-4" />Nuevo proyecto</Button>}</div>;
}

function ProjectsView() {
  const { data, isLoading } = trpc.studio.operations.listProjects.useQuery();
  return <><Header eyebrow="Operación" title="Proyectos en curso" copy="Controla cada producción desde el lead hasta la entrega. El acceso del cliente se limita a los proyectos que se le vinculen." action={<CreateProject />} />{isLoading ? <Loader2 className="animate-spin" /> : !data?.length ? <Empty label="No hay proyectos registrados todavía. Primero crea un cliente y después abre el proyecto." /> : <div className="grid gap-3">{data.map(project => <Card key={project.id}><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-bold">{project.name}</p><p className="mt-1 text-sm text-muted-foreground">{project.service} · Actualizado {new Date(project.updatedAt).toLocaleDateString("es-ES")}</p></div><div className="flex items-center gap-3"><Badge variant="secondary">{project.status.replaceAll("_", " ")}</Badge><span className="text-sm font-semibold">{money(project.price, project.currency)}</span></div></CardContent></Card>)}</div>}</>;
}

function ProductionView() {
  const utils = trpc.useUtils();
  const chains = trpc.studio.production.listChains.useQuery();
  const plugins = trpc.studio.production.listPlugins.useQuery();
  const createChain = trpc.studio.production.createChain.useMutation({ onSuccess: () => { utils.studio.production.listChains.invalidate(); toast.success("Cadena guardada."); } });
  const createPlugin = trpc.studio.production.createPlugin.useMutation({ onSuccess: () => { utils.studio.production.listPlugins.invalidate(); toast.success("Plugin registrado."); } });
  const submitChain = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createChain.mutate({ name: String(data.get("name")), category: String(data.get("category")), genre: String(data.get("genre") || "") || undefined, steps: [] }); event.currentTarget.reset(); };
  const submitPlugin = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createPlugin.mutate({ name: String(data.get("name")), developer: String(data.get("developer")), version: String(data.get("version")), format: "VST3", category: "vocal", tags: [] }); event.currentTarget.reset(); };
  return <><Header eyebrow="Sonido" title="Producción y herramientas" copy="Biblioteca operativa para cadenas de procesamiento, plugins y criterios de entrega. Los datos se añaden sólo desde el equipo de Duck." /><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Cadenas de procesamiento</CardTitle><CardDescription>Workflows reutilizables para voces, mezcla y mastering.</CardDescription></CardHeader><CardContent><form className="mb-5 grid gap-2 sm:grid-cols-3" onSubmit={submitChain}><Input name="name" required placeholder="Nombre de la cadena" /><Input name="category" required defaultValue="vocal" /><Input name="genre" placeholder="Género" /><Button className="sm:col-span-3" type="submit" disabled={createChain.isPending}>Añadir cadena</Button></form>{!chains.data?.length ? <Empty label="Aún no hay cadenas registradas." /> : chains.data.map(chain => <div className="mb-3 rounded-xl bg-muted/60 p-3" key={chain.id}><p className="font-semibold">{chain.name}</p><p className="text-xs text-muted-foreground">{chain.category} · {chain.genre || "sin género"}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Catálogo de plugins</CardTitle><CardDescription>Inventario técnico y estado de herramientas de producción.</CardDescription></CardHeader><CardContent><form className="mb-5 grid gap-2 sm:grid-cols-3" onSubmit={submitPlugin}><Input name="name" required placeholder="Plugin" /><Input name="developer" required placeholder="Desarrollador" /><Input name="version" required placeholder="Versión" /><Button className="sm:col-span-3" type="submit" disabled={createPlugin.isPending}>Registrar plugin</Button></form>{!plugins.data?.length ? <Empty label="Aún no hay plugins registrados." /> : plugins.data.map(plugin => <div className="mb-3 rounded-xl bg-muted/60 p-3" key={plugin.id}><p className="font-semibold">{plugin.name}</p><p className="text-xs text-muted-foreground">{plugin.developer} · {plugin.format} · {plugin.status}</p></div>)}</CardContent></Card></div></>;
}

function FinanceView() {
  const utils = trpc.useUtils();
  const requests = trpc.studio.finance.listPaymentRequests.useQuery();
  const create = trpc.studio.finance.createPaymentRequest.useMutation({ onSuccess: () => { utils.studio.finance.listPaymentRequests.invalidate(); toast.success("Solicitud creada y bloqueada hasta aprobación."); } });
  const decide = trpc.studio.finance.decidePaymentRequest.useMutation({ onSuccess: () => utils.studio.finance.listPaymentRequests.invalidate() });
  const { user } = useAuth();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ title: String(data.get("title")), amount: String(data.get("amount")), currency: "EUR", rationale: String(data.get("rationale")) }); event.currentTarget.reset(); };
  return <><Header eyebrow="Control financiero" title="Cobros bajo aprobación" copy="Ninguna automatización puede cobrar, enviar un enlace de pago o ejecutar una transacción. Solo puede abrir una solicitud pendiente para Duck o Elika." /><div className="grid gap-5 lg:grid-cols-[.9fr_1.4fr]"><Card><CardHeader><CardTitle>Nueva solicitud</CardTitle><CardDescription>Siempre queda en estado pendiente.</CardDescription></CardHeader><CardContent><form className="grid gap-3" onSubmit={submit}><Input name="title" required placeholder="Concepto del cobro" /><Input name="amount" required type="number" min="0.01" step="0.01" placeholder="Importe" /><Textarea name="rationale" required placeholder="Motivo y alcance de la solicitud" /><Button type="submit" disabled={create.isPending}>Crear solicitud pendiente</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Bitácora de decisiones</CardTitle><CardDescription>La aprobación deja evidencia de actor, fecha y motivo.</CardDescription></CardHeader><CardContent className="space-y-3">{!requests.data?.length ? <Empty label="No hay solicitudes de cobro." /> : requests.data.map(request => <div className="rounded-xl border p-4" key={request.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{request.title}</p><p className="mt-1 text-sm text-muted-foreground">{money(request.amount, request.currency)} · {request.rationale}</p></div><Badge variant={request.status === "pending_approval" ? "secondary" : "outline"}>{request.status.replaceAll("_", " ")}</Badge></div>{request.status === "pending_approval" && user?.role === "owner" ? <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => decide.mutate({ paymentRequestId: request.id, decision: "approved", reason: "Aprobación explícita del propietario." })}>Aprobar</Button><Button size="sm" variant="outline" onClick={() => decide.mutate({ paymentRequestId: request.id, decision: "rejected", reason: "No aprobado en esta revisión." })}>Rechazar</Button></div> : null}</div>)}</CardContent></Card></div></>;
}

function InventoryView() {
  const utils = trpc.useUtils();
  const products = trpc.studio.inventory.listProducts.useQuery();
  const create = trpc.studio.inventory.createProduct.useMutation({ onSuccess: () => { utils.studio.inventory.listProducts.invalidate(); toast.success("Producto registrado y validado."); } });
  const propose = trpc.studio.inventory.proposeReplenishment.useMutation({ onSuccess: () => toast.success("Propuesta de reposición registrada para revisión.") });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ sku: String(data.get("sku")), name: String(data.get("name")), stock: Number(data.get("stock")), minStock: Number(data.get("minStock")), pvcSphere: Number(data.get("pvcSphere")), unitPrice: "0" }); event.currentTarget.reset(); };
  return <><Header eyebrow="Ω-MAX Core" title="Inventario verificable" copy="El módulo de stock conserva la validación PVC-U de esferas 1–7. Las reposiciones se registran como propuestas auditables, no como compras automáticas." /><Card className="mb-5"><CardContent className="pt-6"><form className="grid gap-2 md:grid-cols-5" onSubmit={submit}><Input name="sku" required placeholder="SKU" /><Input name="name" required placeholder="Producto" /><Input name="stock" required type="number" min="0" placeholder="Stock" /><Input name="minStock" required type="number" min="0" placeholder="Mínimo" /><Input name="pvcSphere" required type="number" min="1" max="7" placeholder="PVC-U 1–7" /><Button className="md:col-span-5" type="submit" disabled={create.isPending}>Registrar producto con validación PVC-U</Button></form></CardContent></Card>{!products.data?.length ? <Empty label="No hay productos de inventario aún. Este módulo está listo para registrar activos de estudio, consumibles o referencias operativas reales." /> : <div className="grid gap-3 md:grid-cols-2">{products.data.map(product => <Card key={product.id}><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{product.name}</p><p className="mt-1 text-sm text-muted-foreground">{product.sku} · PVC-U esfera {product.pvcSphere}</p></div><div className="flex items-center gap-2"><Badge variant={product.stock <= product.minStock ? "destructive" : "secondary"}>{product.stock} / min. {product.minStock}</Badge>{product.stock <= product.minStock ? <Button size="sm" variant="outline" onClick={() => propose.mutate({ productId: product.id, quantity: Math.max(1, product.minStock * 2 - product.stock), reason: "Stock igual o inferior al mínimo configurado." })}>Proponer reposición</Button> : null}</div></CardContent></Card>)}</div>}</>;
}

function AutomationsView() {
  const utils = trpc.useUtils();
  const automations = trpc.studio.automation.list.useQuery();
  const toggle = trpc.studio.automation.setEnabled.useMutation({ onSuccess: () => utils.studio.automation.list.invalidate() });
  const create = trpc.studio.automation.create.useMutation({ onSuccess: result => { utils.studio.automation.list.invalidate(); toast.success(result.requiresApproval ? "Regla creada: la acción financiera exigirá aprobación." : "Automatización creada."); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ name: String(data.get("name")), trigger: String(data.get("trigger")) as "project_status_change" | "file_uploaded" | "version_approved" | "task_overdue" | "invoice_ready" | "stock_low", action: { type: String(data.get("action")) as "notify_owner" | "notify_client" | "create_task" | "set_status" | "create_payment_request" | "create_replenishment_proposal" } }); event.currentTarget.reset(); };
  return <><Header eyebrow="Flujos gobernados" title="Automatizaciones con trazabilidad" copy="Duck o Elika pueden pausar y reactivar las reglas. Las acciones financieras se convierten automáticamente en solicitudes pendientes, nunca en cobros ejecutados." /><Card className="mb-5"><CardContent className="pt-6"><form className="grid gap-2 md:grid-cols-3" onSubmit={submit}><Input name="name" required placeholder="Nombre de la regla" /><select className="h-10 rounded-md border bg-background px-3 text-sm" name="trigger" defaultValue="file_uploaded"><option value="file_uploaded">Archivo cargado</option><option value="project_status_change">Cambio de estado</option><option value="version_approved">Versión aprobada</option><option value="task_overdue">Tarea vencida</option><option value="invoice_ready">Factura lista</option><option value="stock_low">Stock bajo</option></select><select className="h-10 rounded-md border bg-background px-3 text-sm" name="action" defaultValue="notify_owner"><option value="notify_owner">Notificar a Duck</option><option value="notify_client">Notificar cliente</option><option value="create_task">Crear tarea</option><option value="set_status">Actualizar estado</option><option value="create_payment_request">Proponer cobro (aprobación)</option><option value="create_replenishment_proposal">Proponer reposición</option></select><Button className="md:col-span-3" type="submit" disabled={create.isPending}>Crear regla</Button></form></CardContent></Card>{!automations.data?.length ? <Empty label="Aún no hay reglas creadas. Las reglas se activarán sobre eventos de proyecto, archivos, aprobaciones, tareas, recordatorios e inventario." /> : <div className="grid gap-3">{automations.data.map(item => <Card key={item.id}><CardContent className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-sm text-muted-foreground">Evento: {item.trigger} · Ejecuciones: {item.runs}</p></div><Button variant={item.enabled ? "outline" : "default"} onClick={() => toggle.mutate({ automationId: item.id, enabled: !item.enabled })}>{item.enabled ? "Pausar" : "Activar"}</Button></CardContent></Card>)}</div>}</>;
}

function AuditView() {
  const audit = trpc.studio.audit.list.useQuery();
  const users = trpc.studio.audit.listUsers.useQuery();
  const utils = trpc.useUtils();
  const changeRole = trpc.studio.audit.setUserRole.useMutation({ onSuccess: () => { utils.studio.audit.listUsers.invalidate(); utils.studio.audit.list.invalidate(); toast.success("Rol actualizado y registrado."); } });
  return <><Header eyebrow="Transparencia" title="Bitácora de actividad" copy="Trazabilidad de cambios relevantes, decisiones de automatización, propuestas de reposición y aprobaciones de pagos." /><div className="mb-5 grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Accesos y roles</CardTitle><CardDescription>Solo un propietario puede modificar estos permisos.</CardDescription></CardHeader><CardContent className="space-y-2">{!users.data?.length ? <Empty label="Los usuarios aparecerán tras iniciar sesión." /> : users.data.map(user => <div key={user.id} className="flex items-center justify-between gap-3 rounded-xl bg-muted/50 p-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{user.name || user.email || `Usuario ${user.id}`}</p><p className="text-xs text-muted-foreground">Acceso registrado</p></div><select aria-label={`Rol de ${user.name || user.id}`} className="h-9 rounded-md border bg-background px-2 text-xs" value={user.role} onChange={event => changeRole.mutate({ userId: user.id, role: event.target.value as "owner" | "collaborator" | "client" })}><option value="owner">Owner</option><option value="collaborator">Collaborator</option><option value="client">Client</option></select></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Regla de cobro</CardTitle><CardDescription>La plataforma no ejecuta pagos por sí sola.</CardDescription></CardHeader><CardContent><div className="rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm leading-6"><ShieldCheck className="mb-3 h-5 w-5 text-primary" />Las solicitudes generadas por automatización quedan en <strong>pendiente de aprobación</strong>. Duck o Elika deben resolverlas de forma explícita y la decisión queda en la bitácora.</div></CardContent></Card></div>{!audit.data?.length ? <Empty label="La bitácora se llenará a medida que se creen registros y se ejecuten decisiones." /> : <div className="space-y-2">{audit.data.map(entry => <Card key={entry.id}><CardContent className="flex gap-4 p-4"><Activity className="mt-0.5 h-4 w-4 text-primary" /><div><p className="text-sm font-semibold">{entry.action}</p><p className="text-xs text-muted-foreground">{entry.resource} · {entry.detail || "Sin detalle"} · {new Date(entry.createdAt).toLocaleString("es-ES")}</p></div></CardContent></Card>)}</div>}</>;
}

function DashboardView() {
  const dashboard = trpc.studio.dashboard.useQuery();
  if (dashboard.isLoading) return <Loader2 className="animate-spin" />;
  const data = dashboard.data;
  if (!data || data.mode === "client") return <ClientPortal />;
  const cards = [{ label: "Clientes", value: data.counts.clients, icon: UsersRound }, { label: "Proyectos", value: data.counts.projects, icon: Music2 }, { label: "Tareas abiertas", value: data.counts.openTasks, icon: Clock3 }];
  return <><Header eyebrow="Centro de mando" title="DUCK Ω-MAX" copy="La relación con clientes, producción, operación e inventario en un espacio con reglas claras de autorización." action={<Badge className="w-fit rounded-full px-3 py-1">Sistema exclusivo de Duck</Badge>} /><div className="grid gap-3 md:grid-cols-3">{cards.map(card => <Card key={card.label}><CardContent className="p-5"><card.icon className="mb-5 h-5 w-5 text-primary" /><p className="text-3xl font-extrabold">{card.value}</p><p className="mt-1 text-sm text-muted-foreground">{card.label}</p></CardContent></Card>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Solicitudes que requieren decisión</CardTitle><CardDescription>La capa financiera permanece detenida hasta que Duck o Elika intervengan.</CardDescription></CardHeader><CardContent>{!data.pendingPayments.length ? <Empty label="No hay cobros esperando aprobación." /> : data.pendingPayments.map(request => <div key={request.id} className="mb-2 flex justify-between rounded-xl bg-muted/60 p-3"><span className="text-sm font-medium">{request.title}</span><span className="text-sm">{money(request.amount, request.currency)}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Alertas de stock</CardTitle><CardDescription>Se convierten en propuestas revisables, nunca en pedidos automáticos.</CardDescription></CardHeader><CardContent>{!data.lowStock.length ? <Empty label="No hay alertas de stock." /> : data.lowStock.map(product => <div key={product.id} className="mb-2 flex justify-between rounded-xl bg-muted/60 p-3"><span className="text-sm font-medium">{product.name}</span><Badge variant="destructive">{product.stock} / {product.minStock}</Badge></div>)}</CardContent></Card></div></>;
}

function ProjectUpload({ projectId }: { projectId: number }) {
  const utils = trpc.useUtils();
  const upload = trpc.studio.portal.uploadFile.useMutation({ onSuccess: () => { utils.studio.portal.projectDetail.invalidate({ projectId }); toast.success("Archivo recibido y registrado en el proyecto."); } });
  const [file, setFile] = useState<File | null>(null);
  const [category, setCategory] = useState<"source" | "reference" | "revision" | "master" | "deliverable">("source");
  const submit = () => {
    if (!file) return;
    if (file.size > 25 * 1024 * 1024) { toast.error("El límite inicial es 25 MB por archivo."); return; }
    const reader = new FileReader();
    reader.onload = () => upload.mutate({ projectId, name: file.name, mime: file.type || "application/octet-stream", category, dataUrl: String(reader.result), authorizedForClient: false });
    reader.onerror = () => toast.error("No se pudo leer el archivo.");
    reader.readAsDataURL(file);
  };
  return <div className="mt-4 rounded-xl border border-dashed border-border bg-muted/30 p-4"><p className="text-sm font-semibold">Subir archivo</p><p className="mt-1 text-xs text-muted-foreground">Fuente, referencia o revisión. Máximo 25 MB; cada carga queda registrada.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input type="file" accept="audio/*,.wav,.mp3,.aiff,.zip,.pdf" onChange={event => setFile(event.target.files?.[0] || null)} /><select className="h-10 rounded-md border bg-background px-3 text-sm" value={category} onChange={event => setCategory(event.target.value as typeof category)}><option value="source">Fuente</option><option value="reference">Referencia</option><option value="revision">Revisión</option><option value="master">Master</option><option value="deliverable">Entregable</option></select><Button type="button" disabled={!file || upload.isPending} onClick={submit}>{upload.isPending ? "Subiendo…" : "Registrar carga"}</Button></div></div>;
}

function VersionComments({ versionId }: { versionId: number }) {
  const utils = trpc.useUtils();
  const comments = trpc.studio.portal.listVersionComments.useQuery({ versionId });
  const create = trpc.studio.portal.commentVersion.useMutation({ onSuccess: () => { utils.studio.portal.listVersionComments.invalidate({ versionId }); toast.success("Comentario enviado."); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ versionId, body: String(data.get("body")), timestampSeconds: String(data.get("time") || "") || undefined }); event.currentTarget.reset(); };
  return <div className="mt-3 rounded-xl bg-muted/40 p-3"><form className="flex flex-col gap-2 sm:flex-row" onSubmit={submit}><Input name="time" placeholder="00.000 s" inputMode="decimal" /><Input name="body" required placeholder="Comentario sobre esta versión" /><Button type="submit" size="sm" disabled={create.isPending}>Comentar</Button></form>{comments.data?.length ? <div className="mt-3 space-y-2">{comments.data.map(comment => <p key={comment.id} className="rounded-lg bg-background p-2 text-xs"><span className="mr-2 font-bold text-primary">{comment.timestampSeconds ? `${comment.timestampSeconds}s` : "Nota"}</span>{comment.body}</p>)}</div> : null}</div>;
}

function ProjectWorkspace({ projectId }: { projectId: number }) {
  const detail = trpc.studio.portal.projectDetail.useQuery({ projectId });
  if (detail.isLoading) return <div className="mt-4"><Loader2 className="animate-spin" /></div>;
  if (!detail.data) return null;
  return <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-muted/40 p-4"><p className="font-semibold">Versiones</p>{!detail.data.versions.length ? <p className="mt-2 text-sm text-muted-foreground">No hay versiones para revisar todavía.</p> : <div className="mt-3 space-y-3">{detail.data.versions.map(version => <div key={version.id} className="rounded-xl bg-background p-3"><div className="flex justify-between gap-2"><div><p className="text-sm font-bold">{version.name}</p><p className="text-xs text-muted-foreground">{version.status}</p></div><Badge variant="outline">Revisión</Badge></div><VersionComments versionId={version.id} /></div>)}</div>}</div><div className="rounded-xl bg-muted/40 p-4"><p className="font-semibold">Entregables autorizados</p>{!detail.data.files.length ? <p className="mt-2 text-sm text-muted-foreground">Todavía no hay archivos autorizados para descargar.</p> : <div className="mt-3 space-y-2">{detail.data.files.map(file => <a className="flex items-center justify-between rounded-lg bg-background p-3 text-sm transition hover:bg-accent" key={file.id} href={file.url} target="_blank" rel="noreferrer"><span>{file.name}</span><ArrowUpRight className="h-4 w-4 text-primary" /></a>)}</div>}</div></div>;
}

function ClientPortal() {
  const projects = trpc.studio.operations.listProjects.useQuery();
  const [selectedProjectId, setSelectedProjectId] = useState<number | null>(null);
  return <><Header eyebrow="Portal cliente" title="Tu producción, ordenada" copy="Consulta proyectos vinculados a tu cuenta, carga archivos, revisa versiones autorizadas y deja comentarios con precisión." />{!projects.data?.length ? <Empty label="No hay proyectos vinculados a esta cuenta todavía." /> : <div className="grid gap-3">{projects.data.map(project => <Card key={project.id} className={selectedProjectId === project.id ? "border-primary/50" : ""}><CardContent className="p-5"><button className="flex w-full items-center justify-between text-left" onClick={() => setSelectedProjectId(selectedProjectId === project.id ? null : project.id)}><div><p className="font-bold">{project.name}</p><p className="mt-1 text-sm text-muted-foreground">{project.service}</p></div><Badge>{project.status.replaceAll("_", " ")}</Badge></button><ProjectUpload projectId={project.id} />{selectedProjectId === project.id ? <ProjectWorkspace projectId={project.id} /> : null}</CardContent></Card>)}</div>}</>;
}

export default function Studio() {
  const [location] = useLocation();
  const section = location.split("/")[2] || "dashboard";
  const view = { dashboard: <DashboardView />, crm: <CrmView />, projects: <ProjectsView />, production: <ProductionView />, finance: <FinanceView />, inventory: <InventoryView />, automations: <AutomationsView />, audit: <AuditView />, portal: <ClientPortal /> }[section] || <DashboardView />;
  return <DashboardLayout>{view}</DashboardLayout>;
}
